exit
clear
use_db My;
list_table;
describe diary;
describe_table diary;
add_into_table diary(id=);
select * from diary;
clear
create_table dd();
create_table dd(id:number[not_null, unique, auto_increment], name_command:stringp[df]);
create_table dd(id:number[not_null, unique, auto_increment], name_command:stringp[]);
create_table dd(id:number[not_null, unique, auto_increment], name_command:stringp);
create_table dd(id:number[not_null, unique, auto_increment], name_command:string);
create_table dd(id:number[not_null, unique, auto_increment]);
Traceback (most recent call last):
  File "/home/diary/github/sgbd/main.py", line 370, in <module>
    if check_permission(db, "USAGE", useDatabase) or check_permission(db, "READ", useDatabase):
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diary/github/sgbd/main.py", line 157, in check_permission
    where_clause = where_clause.strip()
                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'where_clause' where it is not associated with a value
cler
clear
;
clear
create_table dd(id:number[not_null, unique, auto_increment], name_command:stringp[df]);
create_table dd();
create_table dd(id:number[not_null, unique, auto_increment], name_command:stringp[df]);
create_table dd();
clear
use_db My;
create_table dd();
create_table dd(id:number[not_null, unique, auto_increment], name_command:string[df]);
